import("//testing/test.gni")

source_set("privacy_cef") {
  sources = [
    "canvas_farbling.cc",
    "canvas_farbling.h",
    "privacy_audit_service.cc",
    "privacy_audit_service.h",
    "privacy_profile.cc",
    "privacy_profile.h",
    "privacy_runtime.cc",
    "privacy_runtime.h",
    "privacy_seed.cc",
    "privacy_seed.h",
    "privacy_switches.cc",
    "privacy_switches.h",
  ]

  deps = [
    "//base",
    "//crypto",
    "//third_party/abseil-cpp:absl",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "canvas_farbling_unittest.cc",
    "privacy_audit_service_unittest.cc",
    "privacy_profile_unittest.cc",
    "privacy_runtime_unittest.cc",
    "privacy_seed_unittest.cc",
  ]
  deps = [
    ":privacy_cef",
    "//base/test:test_support",
    "//testing/gtest",
  ]
}

test("privacy_cef_unit_tests") {
  deps = [
    ":unit_tests",
    "//base",
    "//base/test:run_all_unittests",
    "//base/test:test_support",
  ]
}
